apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arrc-hextris
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tbernacchi/arrc.git
    targetRevision: HEAD
    path: hextris/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: hextris
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - Validate=false
